
/*
===============================================================================
   Magnitude Analysis
===============================================================================

   Purpose:
       - Understand how customers, products, sales, and quantities are
         distributed across different dimensions.
       - Compare the size and contribution of different categories,
         countries, and customers.

   Tables explored:
       - gold_layer.dim_customers
       - gold_layer.dim_products
       - gold_layer.fact_sales

   SQL concepts used:
       - SUM()
       - COUNT()
       - AVG()
       - GROUP BY
       - ORDER BY
       - LEFT JOIN
===============================================================================
*/


-- Find the number of customers in each country
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold_layer.dim_customers
GROUP BY country
ORDER BY total_customers DESC;


-- Find the number of customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold_layer.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


-- Find the number of products in each category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold_layer.dim_products
GROUP BY category
ORDER BY total_products DESC;


-- Find the average product cost in each category
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold_layer.dim_products
GROUP BY category
ORDER BY avg_cost DESC;


-- Find the total revenue generated by each product category
SELECT
    prod.category,
    SUM(sales.sales_amount) AS total_revenue
FROM gold_layer.fact_sales AS sales
LEFT JOIN gold_layer.dim_products AS prod
    ON prod.product_key = sales.product_key
GROUP BY prod.category
ORDER BY total_revenue DESC;


-- Find the total revenue generated by each customer
SELECT
    cust.customer_key,
    cust.first_name,
    cust.last_name,
    SUM(sales.sales_amount) AS total_revenue
FROM gold_layer.fact_sales AS sales
LEFT JOIN gold_layer.dim_customers AS cust
    ON cust.customer_key = sales.customer_key
GROUP BY
    cust.customer_key,
    cust.first_name,
    cust.last_name
ORDER BY total_revenue DESC;


-- Find the total number of items sold in each country
SELECT
    cust.country,
    SUM(sales.quantity) AS total_sold_items
FROM gold_layer.fact_sales AS sales
LEFT JOIN gold_layer.dim_customers AS cust
    ON cust.customer_key = sales.customer_key
GROUP BY cust.country
ORDER BY total_sold_items DESC;

